### ISSUE TITLE
Issue - Can't activate in Blender 2.92

### ISSUE THREAD

**Issue by Draise14** [Symstract/modifier_list#12]
![image](https://user-images.githubusercontent.com/35357409/99029611-e5e42180-2540-11eb-9e9c-daba4082c332.png)

When trying to activate the addon in Blender 2.92, I get an error:

```
Traceback (most recent call last):
  File "E:\3D stuff\Bforartists\Bforartists 2 - 2.5.1\2.92\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.92\scripts\addons\modifier_list\__init__.py", line 60, in register
    addon_name_for_counter=bl_info["name"])
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.92\scripts\addons\modifier_list\addon_registration.py", line 200, in register_bl_classes
    modules = _import_modules(modules)
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.92\scripts\addons\modifier_list\addon_registration.py", line 60, in _import_modules
    module = importlib.import_module("." + mod, package=__package__)
  File "E:\3D stuff\Bforartists\Bforartists 2 - 2.5.1\2.92\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.92\scripts\addons\modifier_list\modules\ui\properties_editor.py", line 5, in <module>
    from .modifiers_ui import modifiers_ui
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.92\scripts\addons\modifier_list\modules\ui\modifiers_ui.py", line 23, in <module>
    from .properties_data_modifier import DATA_PT_modifiers
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\2.92\scripts\addons\modifier_list\modules\ui\properties_data_modifier.py", line 34, in <module>
    BLENDER_VERSION_MAJOR_POINT_MINOR = float(bpy.app.version_string[0:4])
ValueError: could not convert string to float: '2. 5'
```

This has happened on a build from this week, it was working previously.

**Comment by Draise14** [comment]
All in all, this has become my day to day addon - can't wait for the update!

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/99199452-38098a80-276d-11eb-88d0-0040b999ebcd.png)
I think I found the issue, it's with my build version number.

**Comment by Draise14** [comment]
Testing in Blender instead of my own build...

Yes, blender 2.92 works fine, it's my version.

**Comment by Symstract** [comment]
Good that you found the issue. Bforartist seems not to follow the official Blender version number which means that Modifier List won't work well on that. That's because the code uses the version number in different modifiers (currently three modifiers) to decide what to show in which version. That way I don't need to have a different version for every Blender release. But in Bforartists the modifier layouts are stuck showing Blender 2.90 layouts, so there should be things missing (even after I release an update for regular Blender). I don't personally use Bforartist or follow its development so I won't make a separate version for that. :(

Example:

```
    def MULTIRES(self, layout, ob, md):
        # ...
        
        # 2.91 ADDITION
        if BLENDER_VERSION_MAJOR_POINT_MINOR >= 2.91:  # Obviously 2.5 is less that 2.91...
            row = col.row()
            row.enabled = ob.mode == 'SCULPT'
            row.prop(md, "use_sculpt_base_mesh")

       # ...
```

Until Blender 2.90 I didn't need to do this because I could access the built-in layouts from Python. Unfortunately that's not possible anymore.
