### ISSUE TITLE
Cannot enable the addon in Blender 3.0

### ISSUE THREAD

**Issue by AlpineCurd** [Symstract/modifier_list#25]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.0\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\sith1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\modifier_list-master\__init__.py", line 72, in register
    addon_registration.call_register(module_order=module_order)
  File "C:\Users\sith1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\modifier_list-master\addon_registration.py", line 246, in call_register
    mod.register()
  File "C:\Users\sith1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\modifier_list-master\modules\ui\sidebar.py", line 93, in register
    update_sidebar_category()
  File "C:\Users\sith1\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\modifier_list-master\modules\ui\sidebar.py", line 84, in update_sidebar_category
    category = bpy.context.preferences.addons["modifier_list"].preferences.sidebar_category
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'

**Comment by Symstract** [comment]
Thanks for the report. This is not actually a bug, though: the addon's folder needs to be called "modifier_list" but in your case, it's called "modifier_list-master". That's the name Github gives the folder when you download it from the front page of the addon's repository. So you need to download it from https://github.com/Symstract/modifier_list/releases or change the name manually.

I should mention this in the Readme.
