### ISSUE TITLE
Addon ver 1.74 not work on Blender 3.3 Alpha 06/06/2022

### ISSUE THREAD

**Issue by zubenelgennubi** [Symstract/modifier_list#31]
Can't active addon. Error in the console:

Traceback (most recent call last):
  File "D:\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\__init__.py", line 72, in register
    addon_registration.call_register(module_order=module_order)
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\addon_registration.py", line 246, in call_register
    mod.register()
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\preferences.py", line 771, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "NORMAL_EDIT_Defaults" registration error: 'offset' FloatVectorProperty could not register (see previous error)

Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 64, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 23, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 64, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 23, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 64, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 23, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 64, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 23, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
bpy.data.window_managers["WinMan"].(null) = 'A'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 64, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'
Python: Traceback (most recent call last):
  File "D:\ZU\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 23, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'

**Comment by Draise14** [comment]
Got this same error with official release. Blender 3.2 is now official, and 3.2 pulls these similar errors:

```
Traceback (most recent call last):
  File "C:\3D Stuff\Bforartists 3.2.0\3.3\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\3.3\scripts\addons\modifier_list\__init__.py", line 72, in register
    addon_registration.call_register(module_order=module_order)
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\3.3\scripts\addons\modifier_list\addon_registration.py", line 246, in call_register
    mod.register()
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\3.3\scripts\addons\modifier_list\modules\preferences.py", line 771, in register
    bpy.utils.register_class(cls)
ValueError: bpy_struct "NORMAL_EDIT_Defaults" registration error: 'offset' FloatVectorProperty could not register (see previous error)


Python: Traceback (most recent call last):
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 64, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'

Python: Traceback (most recent call last):
  File "C:\Users\drais\AppData\Roaming\Bforartists\Bforartists\3.3\scripts\addons\modifier_list\modules\ui\sidebar.py", line 23, in poll
    prefs = bpy.context.preferences.addons["modifier_list"].preferences
KeyError: 'bpy_prop_collection[key]: key "modifier_list" not found'

```

**Comment by Symstract** [comment]
It seems that there was an accidental renaming in Blender 3.3 which has since been fixed, so everything should be working already.

@Draise14 There shouldn't be errors in 3.2 because the commit that caused the issue was only for 3.3.
