### ISSUE TITLE
Attribute Error when opening search in Blender 3.3.3

### ISSUE THREAD

**Issue by fleity** [Symstract/modifier_list#38]
Any time I open the search box (Space) there are errors from modifier list in the console

 `Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\bl_symlink\scripts\addons\tx_layer\operators\delete_layer.py", line 23, in poll
    return mat.layer_list and mat.layer_index >= 0 and mat.layer_index < len(mat.layer_list)
AttributeError: 'NoneType' object has no attribute 'layer_list'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\bl_symlink\scripts\addons\tx_layer\operators\set_mask.py", line 25, in poll
    return mat.layer_list and mat.layer_index >= 0 and mat.layer_index < len(mat.layer_list)
AttributeError: 'NoneType' object has no attribute 'layer_list'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\bl_symlink\scripts\addons\tx_layer\operators\node_group.py", line 347, in poll
    return mat.layer_list
AttributeError: 'NoneType' object has no attribute 'layer_list'`

in scenes created with blender <3.2 I also get another attribute error whenever I select any object 
`AttributeError: 'Context' object has no attribute 'object'
File "C:\Program Files\Blender Foundation\bl_symlink\scripts\addons\modifier_list\modules\properties.py", line 13, in modifier_active_index_get
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\bl_symlink\scripts\addons\modifier_list\modules\properties.py", line 14, in modifier_active_index_get
    ob = get_ml_active_object()
  File "C:\Program Files\Blender Foundation\bl_symlink\scripts\addons\modifier_list\modules\utils.py", line 47, in get_ml_active_object
    ob = context.object
AttributeError: 'Context' object has no attribute 'object'
File "C:\Program Files\Blender Foundation\bl_symlink\scripts\addons\modifier_list\modules\properties.py", line 13, in modifier_active_index_get`

both seem to be not critical for the add on to work, but would be nice if they could be fixed / prevented
blender 3.3.3 lts & modifier list 1.7.4

thanks

**Comment by fleity** [comment]
I noticed the errors seem to be specific to a combinaton of auto rig pro and modifier list in some of my files. 
As I can not reliably reproduce the error I would mark it as resolved, sorry for the disturbance.
